name: tryzeon
description: "Tryzeon App"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+2
  smooth_page_indicator: ^1.1.0
  image_picker: ^1.0.4
  adaptive_platform_ui: ^0.1.95
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.0.0
  flutter_markdown: ^0.7.4
  flutter_svg: ^2.0.10
  url_launcher: ^6.2.1
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  gal: ^2.3.2
  google_fonts: ^6.3.2
  flutter_cache_manager: ^3.4.1
  flutter_image_compress: ^2.4.0
  mime: ^2.0.0
  flutter_dotenv: ^5.2.1

  path: any
  typed_result: ^2.0.0
  cached_network_image: ^3.4.1
  cached_query_flutter: ^3.3.1
  cached_storage: ^3.2.2
  hooks_riverpod: ^3.1.0
  flutter_hooks: ^0.21.3+1
  talker_flutter: ^5.1.9
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  assets:
    - .env
    - assets/images/ads/
    - assets/images/profile/
    - assets/images/logo/

  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo/tryzeon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo/tryzeon.png"
